### PR TITLE
Change author files and references to full names

### PR DESCRIPTION
**Pull request by frederickobrien**
We spoke about this ages ago and it seemed like a good thing to tidy up. All author files are now full names, with the references to them in posts changed in kind. 

I've removed special characters from the file names, so `andre-dack.md` rather than `andré-dack.md` and so on. I remember this being a slight annoyance for you before @andrewbridge so thought it best to change. One less thing to go wrong.

This should be fairly straightforward but wanted to do a review given this means changing hundreds of files in one go. I used VSC's find and replace functionality to do this and it should be fine, but something could have slipped through the net.

**Edit:** Got to be careful here. Commits are passing preview checks even when the data is faulty.

### CODE REVIEW

**Comment by frederickobrien** [comment]
Most of the way there now. Wound up doing multiple-author articles manually, while André has been a bit of a problem child because some of his author credits have the accent on the e and others don't.

**Comment by andrewbridge** [comment]
> Most of the way there now. Wound up doing multiple-author articles manually, while André has been a bit of a problem child because some of his author credits have the accent on the e and others don't.

Probably too late now but you don't need to worry _too_ much about the accent as we currently use [Lodash's deburr function](https://docs-lodash.com/v4/deburr/) when matching author references to author files. The issue we ran into was the review dropbox not running similar fuzzy matching when attempting to find pre-existing content. The rewrite of the data processor would ultimately mean the same matching logic could be used everywhere in the future.

Either way, going through and making things alphanumeric isn't going to do any harm here.

**Comment by andrewbridge** [comment]
Re: Faulty data passing: The data processor should probably be more stringent about this, it's currently handled by [this gross function](https://github.com/audioxide/data-processor/blob/main/generate.js#L391), on [L443](https://github.com/audioxide/data-processor/blob/main/generate.js#L443) we straight up just remove author information entirely if a match isn't found.

Should we throw an error to kill the whole build instead?

**Comment by frederickobrien** [comment]
> 
> 
> Re: Faulty data passing: The data processor should probably be more stringent about this, it's currently handled by [this gross function](https://github.com/audioxide/data-processor/blob/main/generate.js#L391), on [L443](https://github.com/audioxide/data-processor/blob/main/generate.js#L443) we straight up just remove author information entirely if a match isn't found.
> 
> Should we throw an error to kill the whole build instead?

I reckon so yeah, it does a real number on the site when author file references are wrong (which they hopefully aren't now). Empty pages, homepage popping up where reviews should be. Would be a good extra layer between human error and the site tanking.

**Comment by andrewbridge** [comment]
Just pushed a change to both data-processor and bumped the data-processor package in that last commit. You should expect things to fail if an author reference can't be resolved now.

**Comment by andrewbridge** [comment]
Seems to be working and showing up our spelling failures haha

[`Error: [Author resolution] top-10-albums-of-2019: Error: Author reference 'micheal-clark' could not be resolved.`](https://github.com/audioxide/data/pull/62/checks?check_run_id=2317535643#step:10:88)

**Comment by frederickobrien** [comment]
> 
> 
> Seems to be working and showing up our spelling failures haha
> 
> [`Error: [Author resolution] top-10-albums-of-2019: Error: Author reference 'micheal-clark' could not be resolved.`](https://github.com/audioxide/data/pull/62/checks?check_run_id=2317535643#step:10:88)

Aha, I've never been happier to see something not work. All author references now sorted. Unless I've ballsed up the en-masse replacement this should be in good shape? Probably worth having a click around to be on the safe side but not sure how to be 100% safe short of checking every single page... which will not be happening.

Not the sexiest update but a good one to get done for scalability, uniformity, etc. In a way the finickiness of this PR in itself shows the value of having a uniform system going forward.

**Comment by andrewbridge** [comment]
Ultimately, that change should mean that the build wouldn't pass if your references didn't all match. The only thing you could've possibly done is misreferenced an author, and using full name slugs makes it even harder to do that than before. Will have a click around, but otherwise I reckon this is good to go.

**Comment by andrewbridge** [comment]
Just done a spot check using "Feed your head" and it all looks good!

**Review by andrewbridge — APPROVED** [review]
LGTM

**Comment by frederickobrien** [comment]
What could possibly go wrong?

**Pull request merged**
